name: Generate documentation

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Generate documentation
        run: make tidy-doc

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: doc
          path: doc/google-play

  push:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        name: Download documentation
        with:
          pattern: doc
          path: doc
          merge-multiple: true
      - name: Push documentation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: doc
          build_dir: doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
